/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Session */
        get: operations["read_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card Transactions */
        get: operations["card_transactions_api_cards__card_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Public Token */
        post: operations["exchange_public_token_api_connections_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/link-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Link Token */
        post: operations["create_link_token_api_connections_link_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_api_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_connections__connection_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}/update-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Update Link Token */
        post: operations["create_update_link_token_api_connections__connection_id__update_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transaction-limit-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transaction Limit Alerts */
        get: operations["list_transaction_limit_alerts_api_transaction_limit_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transaction-limitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transaction Limitations */
        get: operations["list_transaction_limitations_api_transaction_limitations_get"];
        put?: never;
        /** Create Transaction Limitation */
        post: operations["create_transaction_limitation_api_transaction_limitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transaction-limitations/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction Limitation */
        delete: operations["delete_transaction_limitation_api_transaction_limitations__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction Limitation */
        patch: operations["update_transaction_limitation_api_transaction_limitations__rule_id__patch"];
        trace?: never;
    };
    "/api/transactions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Transactions */
        get: operations["search_transactions_api_transactions_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/plaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Plaid Webhook */
        post: operations["receive_plaid_webhook_api_webhooks_plaid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllTimeWindow */
        AllTimeWindow: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "all_time";
        };
        /** BankConnectionResponse */
        BankConnectionResponse: {
            /**
             * Action
             * @default none
             */
            action: string;
            /**
             * Bank
             * @enum {string}
             */
            bank: "capital-one" | "chase" | "citi" | "wells-fargo";
            /** Cache As Of */
            cache_as_of?: string | null;
            /** Card Count */
            card_count: number;
            /** Connected */
            connected: boolean;
            /** Connection Id */
            connection_id: string | null;
            /** Consent Expiration At */
            consent_expiration_at: string | null;
            /** Display Name */
            display_name: string;
            /** Institution Name */
            institution_name: string | null;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Provider Update At */
            last_provider_update_at: string | null;
            /** Last Successful Sync At */
            last_successful_sync_at: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /**
             * Message
             * @default Not connected.
             */
            message: string;
            /** Refresh Supported */
            refresh_supported: boolean;
            /**
             * State
             * @default disconnected
             */
            state: string;
        };
        /** CardResponse */
        CardResponse: {
            /**
             * Bank
             * @enum {string}
             */
            bank: "capital-one" | "chase" | "citi" | "wells-fargo";
            /** Bank Display Name */
            bank_display_name: string;
            /** Connection Id */
            connection_id: string;
            /** Id */
            id: string;
            /** Last Successful Sync At */
            last_successful_sync_at?: string | null;
            /** Mask */
            mask: string | null;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
            /**
             * State
             * @default ready
             */
            state: string;
        };
        /** CardTransactionGroup */
        CardTransactionGroup: {
            card: components["schemas"]["CardResponse"];
            /** Has More */
            has_more: boolean;
            /** Match Count */
            match_count: number;
            /** Next Cursor */
            next_cursor: string | null;
            /** Transactions */
            transactions: components["schemas"]["TransactionMatch"][];
        };
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** Banks */
            banks: components["schemas"]["BankConnectionResponse"][];
            /** Environment */
            environment: string;
            /** Production Item Count */
            production_item_count: number;
            /** Production Item Limit */
            production_item_limit: number;
            /** Uses Demo Bank */
            uses_demo_bank: boolean;
        };
        /** CreateLinkTokenRequest */
        CreateLinkTokenRequest: {
            /**
             * Bank
             * @enum {string}
             */
            bank: "capital-one" | "chase" | "citi" | "wells-fargo";
            /**
             * Confirm Trial Slot
             * @default false
             */
            confirm_trial_slot: boolean;
        };
        /** CreateTransactionLimitationRequest */
        CreateTransactionLimitationRequest: {
            /** Card Ids */
            card_ids?: string[];
            /**
             * Card Scope
             * @enum {string}
             */
            card_scope: "all_cards" | "selected_cards";
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
            /** Keyword */
            keyword: string;
            /** Threshold */
            threshold: number;
            /** Window */
            window: components["schemas"]["AllTimeWindow"] | components["schemas"]["RollingWindow"];
        };
        /** EvaluatedAllTimeWindow */
        EvaluatedAllTimeWindow: {
            /** Days */
            days?: null;
            /** Effective End Date */
            effective_end_date?: null;
            /** Effective Start Date */
            effective_start_date?: null;
            /** End Date */
            end_date?: null;
            /** Start Date */
            start_date?: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "all_time";
        };
        /** EvaluatedRollingWindow */
        EvaluatedRollingWindow: {
            /** Days */
            days: number;
            /**
             * Effective End Date
             * Format: date
             */
            effective_end_date: string;
            /**
             * Effective Start Date
             * Format: date
             */
            effective_start_date: string;
            /** End Date */
            end_date?: null;
            /** Start Date */
            start_date?: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rolling";
        };
        /** ExchangePublicTokenRequest */
        ExchangePublicTokenRequest: {
            /**
             * Bank
             * @enum {string}
             */
            bank: "capital-one" | "chase" | "citi" | "wells-fargo";
            /** Institution Id */
            institution_id: string;
            /** Institution Name */
            institution_name: string;
            /** Public Token */
            public_token: string;
        };
        /** ExchangeResponse */
        ExchangeResponse: {
            /**
             * Bank
             * @enum {string}
             */
            bank: "capital-one" | "chase" | "citi" | "wells-fargo";
            /** Card Count */
            card_count: number;
            /** Connection Id */
            connection_id: string;
            /** Institution Name */
            institution_name: string;
            /** Sync Job Id */
            sync_job_id: string | null;
        };
        /** GroupedSearchResponse */
        GroupedSearchResponse: {
            /** Cache As Of */
            cache_as_of: string | null;
            /** Card Count */
            card_count: number;
            /** Groups */
            groups: components["schemas"]["CardTransactionGroup"][];
            /** Query */
            query: string;
            /** Total Matches */
            total_matches: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkTokenResponse */
        LinkTokenResponse: {
            /** Bank */
            bank: string;
            /** Consumes Trial Slot */
            consumes_trial_slot: boolean;
            /** Link Token */
            link_token: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "new" | "update";
            /** Production Item Count */
            production_item_count: number;
            /** Production Item Limit */
            production_item_limit: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OwnerResponse */
        OwnerResponse: {
            /** Email */
            email: string;
            /** Id */
            id: string;
        };
        /** RollingWindow */
        RollingWindow: {
            /** Days */
            days: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rolling";
        };
        /** SessionResponse */
        SessionResponse: {
            /** Csrf Token */
            csrf_token: string;
            owner: components["schemas"]["OwnerResponse"];
        };
        /** SyncJobResponse */
        SyncJobResponse: {
            /** Connection Id */
            connection_id: string;
            /** Job Id */
            job_id: string;
            /** Refresh Requested */
            refresh_requested: boolean;
            /** State */
            state: string;
            /** Trigger */
            trigger: string;
        };
        /** SyncStatusEntry */
        SyncStatusEntry: {
            /** Bank */
            bank: string;
            /** Connection Id */
            connection_id: string;
            /** Last Error Code */
            last_error_code: string | null;
            /** State */
            state: string;
            /** Trigger */
            trigger: string | null;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Jobs */
            jobs: components["schemas"]["SyncStatusEntry"][];
            /** Queued */
            queued: number;
            /** Running */
            running: number;
        };
        /** TransactionLimitAlertListResponse */
        TransactionLimitAlertListResponse: {
            /** Alerts */
            alerts: components["schemas"]["TransactionLimitAlertResponse"][];
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Cache As Of */
            cache_as_of: string | null;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /** TransactionLimitAlertResponse */
        TransactionLimitAlertResponse: {
            card: components["schemas"]["CardResponse"];
            /** Keyword */
            keyword: string;
            /** Match Count */
            match_count: number;
            /** Pending Count */
            pending_count: number;
            /** Rule Id */
            rule_id: string;
            /** Threshold */
            threshold: number;
            /** Window */
            window: components["schemas"]["EvaluatedAllTimeWindow"] | components["schemas"]["EvaluatedRollingWindow"];
        };
        /** TransactionLimitationListResponse */
        TransactionLimitationListResponse: {
            /** Cards */
            cards: components["schemas"]["CardResponse"][];
            /** Rules */
            rules: components["schemas"]["TransactionLimitationResponse"][];
        };
        /** TransactionLimitationResponse */
        TransactionLimitationResponse: {
            /** Card Ids */
            card_ids: string[];
            /**
             * Card Scope
             * @enum {string}
             */
            card_scope: "all_cards" | "selected_cards";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Keyword */
            keyword: string;
            /** Needs Card Selection */
            needs_card_selection: boolean;
            /** Threshold */
            threshold: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Window */
            window: components["schemas"]["AllTimeWindow"] | components["schemas"]["RollingWindow"];
        };
        /** TransactionMatch */
        TransactionMatch: {
            /** Amount Cents */
            amount_cents: number;
            /** Authorized Date */
            authorized_date: string | null;
            /** Card Id */
            card_id: string;
            /** Category */
            category: string | null;
            /** Currency Code */
            currency_code: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Merchant Name */
            merchant_name: string | null;
            /** Original Description */
            original_description: string | null;
            /** Pending */
            pending: boolean;
            /** Posted Date */
            posted_date: string | null;
        };
        /** UpdateTransactionLimitationRequest */
        UpdateTransactionLimitationRequest: {
            /** Card Ids */
            card_ids?: string[] | null;
            /** Card Scope */
            card_scope?: ("all_cards" | "selected_cards") | null;
            /** Is Enabled */
            is_enabled?: boolean | null;
            /** Keyword */
            keyword?: string | null;
            /** Threshold */
            threshold?: number | null;
            /** Window */
            window?: (components["schemas"]["AllTimeWindow"] | components["schemas"]["RollingWindow"]) | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    card_transactions_api_cards__card_id__transactions_get: {
        parameters: {
            query?: {
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardTransactionGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
        };
    };
    exchange_public_token_api_connections_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangePublicTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_token_api_connections_link_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLinkTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_connections__connection_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_update_link_token_api_connections__connection_id__update_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    list_transaction_limit_alerts_api_transaction_limit_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionLimitAlertListResponse"];
                };
            };
        };
    };
    list_transaction_limitations_api_transaction_limitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionLimitationListResponse"];
                };
            };
        };
    };
    create_transaction_limitation_api_transaction_limitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionLimitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionLimitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_limitation_api_transaction_limitations__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_limitation_api_transaction_limitations__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionLimitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionLimitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_transactions_api_transactions_search_get: {
        parameters: {
            query?: {
                q?: string;
                per_card_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupedSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_plaid_webhook_api_webhooks_plaid_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
