"""core schema

Revision ID: 0001
Revises:
Create Date: 2026-08-19 08:25:40.145391
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('plaid_user_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('webhook_type', sa.String(length=64), nullable=True),
    sa.Column('webhook_code', sa.String(length=64), nullable=True),
    sa.Column('plaid_item_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_sha256', name='ux_webhook_payload')
    )
    op.create_table('bank_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('bank_slug', sa.String(length=32), nullable=False),
    sa.Column('institution_id', sa.String(length=64), nullable=False),
    sa.Column('institution_name', sa.String(length=128), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=128), nullable=True),
    sa.Column('plaid_environment', sa.String(length=16), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=16), nullable=False),
    sa.Column('access_token_ciphertext', sa.Text(), nullable=True),
    sa.Column('access_token_nonce', sa.String(length=32), nullable=True),
    sa.Column('access_token_key_version', sa.Integer(), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('consent_expiration_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('last_successful_sync_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('last_provider_update_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('last_refresh_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('refresh_supported', sa.Boolean(), nullable=False),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('removed_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_item_id')
    )
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_connections_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ux_bank_connections_active_institution', ['owner_id', 'institution_id'], unique=True, sqlite_where=sa.text("lifecycle_status = 'active'"))

    op.create_table('owner_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('revoked_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('last_seen_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sha256')
    )
    with op.batch_alter_table('owner_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_sessions_owner_id'), ['owner_id'], unique=False)

    op.create_table('card_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('official_name', sa.String(length=256), nullable=True),
    sa.Column('mask', sa.String(length=8), nullable=True),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    with op.batch_alter_table('card_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_accounts_connection_id'), ['connection_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('started_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('finished_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_jobs_state_run_after', ['state', 'run_after'], unique=False)
        batch_op.create_index('ux_sync_jobs_active_connection', ['connection_id'], unique=True, sqlite_where=sa.text("state IN ('queued', 'running')"))

    op.create_table('sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('starting_cursor', sa.Text(), nullable=True),
    sa.Column('ending_cursor', sa.Text(), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('modified_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('plaid_request_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('finished_at', app.models.UtcDateTime(length=32), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_connection_id'), ['connection_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('card_account_id', sa.String(length=36), nullable=False),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('merchant_name', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('original_description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.models.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_account_id'], ['card_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_card_account_id'), ['card_account_id'], unique=False)
        batch_op.create_index('ix_transactions_card_posted', ['card_account_id', 'posted_date'], unique=False)
        batch_op.create_index('ix_transactions_search_text', ['search_text'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_search_text')
        batch_op.drop_index('ix_transactions_card_posted')
        batch_op.drop_index(batch_op.f('ix_transactions_card_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_connection_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ux_sync_jobs_active_connection', sqlite_where=sa.text("state IN ('queued', 'running')"))
        batch_op.drop_index('ix_sync_jobs_state_run_after')

    op.drop_table('sync_jobs')
    with op.batch_alter_table('card_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_accounts_connection_id'))

    op.drop_table('card_accounts')
    with op.batch_alter_table('owner_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_sessions_owner_id'))

    op.drop_table('owner_sessions')
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index('ux_bank_connections_active_institution', sqlite_where=sa.text("lifecycle_status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_bank_connections_owner_id'))

    op.drop_table('bank_connections')
    op.drop_table('webhook_receipts')
    op.drop_table('owners')
    # ### end Alembic commands ###
